### ISSUE TITLE
When I open it there is no response？

### ISSUE THREAD

**Issue by Noruens** [dwunger/pak-merge-helper#25]
**### I use Google Translate to communicate, maybe the sentence will be a bit strange**...

When I run it, the taskbar seems to respond but it just flashes something, I can't see it and there is no error message ,Maybe there is something wrong with my system?

This is my system info:
Version: Windows 11 Pro
Version: 21H2
OS version: 22000.556

**Comment by dwunger** [comment]
From file explorer, navigate to:
%appdata%/GaziGuard/config.ini

If nothing is clearly missing or incorrect, share your error log from:
%appdata%/GaziGuard/LOG_INFO.log

Please share if any information related to your fix! This will be used to improve the application in future patches.

**Comment by Noruens** [comment]
Now I'm guessing that maybe I didn't configure the config.ini correctly, but I don't see a tutorial on Github for configuring it, and I'm getting a headache with a screen full of English...(Despite the availability of a translator, parts of the translation are still difficult to understand)



There is my [config.ini] and [LOG_INFO.log]. (For upload conifg, I change the extensions)
[LOG_INFO.log](https://github.com/dwunger/gazi-guard/files/12328023/LOG_INFO.log)
[config.txt](https://github.com/dwunger/gazi-guard/files/12328024/config.txt)

**Comment by dwunger** [comment]
The application typically finds the required files automatically, removing the necessity of working with the 'config.ini' file. In the latest release (v1.0.4), _GaziGuard_ will prompt you to choose any unlocated files upon launch.

Example config.ini:
`
[Scan]
deep_scan = False
force_refresh_source_scripts = False
force_refresh_mod_scripts = False

[Paths]
source_pak_0 = data0.pak
source_pak_1 = data1.pak
;_example:_
**mod_pak =  C:\Program Files (x86)\Steam\steamapps\common\Dying Light 2\ph\source\data6.pak**

[Workspace]
;_example:_
**target = C:\Program Files (x86)\Steam\steamapps\common\Dying Light 2\ph\source**

[Meld]
enable = True
path = C:\Program Files (x86)\Meld/Meld.exe

[Backups]
enable = True
count = 10

[Misc]
overwrite_default = True
hide_unpacked_content = True
notifications = False
always_on_top = True
`

If you don't mind my asking, what language do you prefer?

**Comment by Noruens** [comment]
Great, now it's working! Thank you! This is a great tool. Thanks for making it.
About language,I'm from China. Chinese is easier for me, But I don't want to cause you any trouble. English is enough.
